"""Initial migration

Revision ID: 4b870803f72a
Revises: 
Create Date: 2024-10-29 12:45:29.804768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b870803f72a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_number', sa.String(length=10), nullable=False),
    sa.Column('credit_hours', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_course_number'), ['course_number'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('student_class', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_student_number'), ['student_number'], unique=True)

    op.create_table('prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_number', sa.String(length=10), nullable=False),
    sa.Column('prerequisite_number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['course_number'], ['courses.course_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_identifier', sa.Integer(), nullable=False),
    sa.Column('course_number', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('instructor', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_number'], ['courses.course_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_section_identifier'), ['section_identifier'], unique=True)

    op.create_table('grade_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.Integer(), nullable=False),
    sa.Column('section_identifier', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['section_identifier'], ['sections.section_identifier'], ),
    sa.ForeignKeyConstraint(['student_number'], ['students.student_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_reports_student_number'), ['student_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_reports_student_number'))

    op.drop_table('grade_reports')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_section_identifier'))

    op.drop_table('sections')
    op.drop_table('prerequisites')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_number'))

    op.drop_table('students')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_course_number'))

    op.drop_table('courses')
    # ### end Alembic commands ###
